/*
 * 1Click Swap API
 *
 * API for One-Click Swaps
 *
 * The version of the OpenAPI document: 0.1.10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnyInputQuoteWithdrawal {
    /// Withdrawal status
    #[serde(rename = "status")]
    pub status: Status,
    /// Amount out in readable format
    #[serde(rename = "amountOutFormatted")]
    pub amount_out_formatted: String,
    /// Amount out in USD
    #[serde(rename = "amountOutUsd")]
    pub amount_out_usd: String,
    /// Amount out in smallest unit
    #[serde(rename = "amountOut")]
    pub amount_out: String,
    /// Withdrawal fee in readable format
    #[serde(rename = "withdrawFeeFormatted")]
    pub withdraw_fee_formatted: String,
    /// Withdrawal fee in smallest unit
    #[serde(rename = "withdrawFee")]
    pub withdraw_fee: String,
    /// Withdrawal fee in USD
    #[serde(rename = "withdrawFeeUsd")]
    pub withdraw_fee_usd: String,
    /// Timestamp of withdrawal
    #[serde(rename = "timestamp")]
    pub timestamp: String,
    /// Transaction hash
    #[serde(rename = "hash")]
    pub hash: String,
}

impl AnyInputQuoteWithdrawal {
    pub fn new(status: Status, amount_out_formatted: String, amount_out_usd: String, amount_out: String, withdraw_fee_formatted: String, withdraw_fee: String, withdraw_fee_usd: String, timestamp: String, hash: String) -> AnyInputQuoteWithdrawal {
        AnyInputQuoteWithdrawal {
            status,
            amount_out_formatted,
            amount_out_usd,
            amount_out,
            withdraw_fee_formatted,
            withdraw_fee,
            withdraw_fee_usd,
            timestamp,
            hash,
        }
    }
}
/// Withdrawal status
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "SUCCESS")]
    Success,
    #[serde(rename = "FAILED")]
    Failed,
}

impl Default for Status {
    fn default() -> Status {
        Self::Success
    }
}

