/*
 * 1Click Swap API
 *
 * API for One-Click Swaps
 *
 * The version of the OpenAPI document: 0.1.6
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppFee {
    /// Intents Account ID where this fee will be transferred to
    #[serde(rename = "recipient")]
    pub recipient: String,
    /// Fee for this recipient as part of amountIn in basis points (1/100th of a percent), e.g. 100 for 1% fee
    #[serde(rename = "fee")]
    pub fee: f64,
}

impl AppFee {
    pub fn new(recipient: String, fee: f64) -> AppFee {
        AppFee {
            recipient,
            fee,
        }
    }
}

