/*
 * 1Click Swap API
 *
 * API for One-Click Swaps
 *
 * The version of the OpenAPI document: 0.1.8
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BadRequestResponse {
    #[serde(rename = "message")]
    pub message: String,
}

impl BadRequestResponse {
    pub fn new(message: String) -> BadRequestResponse {
        BadRequestResponse {
            message,
        }
    }
}

