/*
 * 1Click Swap API
 *
 * API for One-Click Swaps
 *
 * The version of the OpenAPI document: 0.1.10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAnyInputQuoteWithdrawals {
    /// ID of the destination asset.
    #[serde(rename = "asset")]
    pub asset: String,
    /// Recipient address
    #[serde(rename = "recipient")]
    pub recipient: String,
    /// Affiliate recipient address
    #[serde(rename = "affiliateRecipient")]
    pub affiliate_recipient: String,
    /// Details of withdrawals
    #[serde(rename = "withdrawals", skip_serializing_if = "Option::is_none")]
    pub withdrawals: Option<Box<models::AnyInputQuoteWithdrawal>>,
}

impl GetAnyInputQuoteWithdrawals {
    pub fn new(asset: String, recipient: String, affiliate_recipient: String) -> GetAnyInputQuoteWithdrawals {
        GetAnyInputQuoteWithdrawals {
            asset,
            recipient,
            affiliate_recipient,
            withdrawals: None,
        }
    }
}

