/*
 * 1Click Swap API
 *
 * API for One-Click Swaps
 *
 * The version of the OpenAPI document: 0.1.10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuoteResponse {
    /// Unique identifier for request tracing and debugging
    #[serde(rename = "correlationId")]
    pub correlation_id: String,
    /// Timestamp in ISO format that was used to derive the deposit address
    #[serde(rename = "timestamp")]
    pub timestamp: String,
    /// Signature of the 1Click service confirming the quote for the specific deposit address. Must be saved on the client side (along with the whole quote) in order to resolve any disputes or mistakes.
    #[serde(rename = "signature")]
    pub signature: String,
    /// User request
    #[serde(rename = "quoteRequest")]
    pub quote_request: Box<models::QuoteRequest>,
    /// Response containing the deposit address for sending the `amount` of `originAsset` and the expected output amount.
    #[serde(rename = "quote")]
    pub quote: Box<models::Quote>,
}

impl QuoteResponse {
    pub fn new(correlation_id: String, timestamp: String, signature: String, quote_request: models::QuoteRequest, quote: models::Quote) -> QuoteResponse {
        QuoteResponse {
            correlation_id,
            timestamp,
            signature,
            quote_request: Box::new(quote_request),
            quote: Box::new(quote),
        }
    }
}

