/*
 * 1Click Swap API
 *
 * API for One-Click Swaps
 *
 * The version of the OpenAPI document: 0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Quote {
    /// The deposit address on the chain of `originAsset` in case if `depositType` is `ORIGIN_CHAIN`.  The deposit address inside of near intents (the verifier smart contract) in case if `depositType` is `INTENTS`.
    #[serde(rename = "depositAddress", skip_serializing_if = "Option::is_none")]
    pub deposit_address: Option<String>,
    /// Amount of the origin asset
    #[serde(rename = "amountIn")]
    pub amount_in: String,
    /// Amount of the origin asset in readable format
    #[serde(rename = "amountInFormatted")]
    pub amount_in_formatted: String,
    /// Amount of the origin assets equivalent in USD
    #[serde(rename = "amountInUsd")]
    pub amount_in_usd: String,
    /// Minimum amount of the origin asset that will be used for swap
    #[serde(rename = "minAmountIn")]
    pub min_amount_in: String,
    /// Amount of the destination asset
    #[serde(rename = "amountOut")]
    pub amount_out: String,
    /// Amount of the destination asset in readable format
    #[serde(rename = "amountOutFormatted")]
    pub amount_out_formatted: String,
    /// Amount of the destination asset equivalent in USD
    #[serde(rename = "amountOutUsd")]
    pub amount_out_usd: String,
    /// Minimum amount with slippage taken into account
    #[serde(rename = "minAmountOut")]
    pub min_amount_out: String,
    /// Time when the deposit address will become inactive and funds might be lost
    #[serde(rename = "deadline", skip_serializing_if = "Option::is_none")]
    pub deadline: Option<String>,
    /// Time when the deposit address will become cold and swap processing will take more time
    #[serde(rename = "timeWhenInactive", skip_serializing_if = "Option::is_none")]
    pub time_when_inactive: Option<String>,
    /// Estimated time in seconds for swap to be executed after the deposit transaction is confirmed
    #[serde(rename = "timeEstimate")]
    pub time_estimate: f64,
}

impl Quote {
    pub fn new(amount_in: String, amount_in_formatted: String, amount_in_usd: String, min_amount_in: String, amount_out: String, amount_out_formatted: String, amount_out_usd: String, min_amount_out: String, time_estimate: f64) -> Quote {
        Quote {
            deposit_address: None,
            amount_in,
            amount_in_formatted,
            amount_in_usd,
            min_amount_in,
            amount_out,
            amount_out_formatted,
            amount_out_usd,
            min_amount_out,
            deadline: None,
            time_when_inactive: None,
            time_estimate,
        }
    }
}

