/*
 * 1Click Swap API
 *
 * API for One-Click Swaps
 *
 * The version of the OpenAPI document: 0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionDetails {
    /// Transaction hash
    #[serde(rename = "hash")]
    pub hash: String,
    /// Explorer URL for the transaction
    #[serde(rename = "explorerUrl")]
    pub explorer_url: String,
}

impl TransactionDetails {
    pub fn new(hash: String, explorer_url: String) -> TransactionDetails {
        TransactionDetails {
            hash,
            explorer_url,
        }
    }
}

